pipeline { 
  agent any
 
  tools {nodejs "node"}
 
  stages {	  
    stage('Cloning Git') {
      steps {
        git 'https://github.com/avmesquita/CTT-Api-node'
      }
    }        
    stage('Install dependencies') {
      steps {
        sh 'npm install'
      }
    }     
  }
}
